// src/components/sidebar/Index.vue
<template>
  <div
    id="sidebar"
    class=""
    :class="
      twMerge(
        'relative flex w-[312px] select-none flex-col justify-between px-xs transition-all duration-300 md:p-xl',
        !systemStore.isCollapseSidebar
          ? 'w-[312px]'
          : 'w-[60px] md:w-[80px]',
      )
    "
  >
    <div class="navigation flex flex-col gap-6 pt-md">
      <div class="flex w-full items-center gap-2">
        <img src="/logo.png" alt="logo" class="h-10" />
        <span
          class="text-lg font-bold text-gray-900"
          v-if="!systemStore.isCollapseSidebar"
        >
          SwiftPOD
        </span>
      </div>

      <div class="menu flex flex-col gap-xs">
        <template v-for="i in sidebar" :key="i.id">
          <SidebarItem :data="i" />
        </template>
      </div>
    </div>
    <div
      id="footer"
      class="relative flex h-min items-center gap-lg overflow-hidden border-t border-gray-200 px-sm py-lg pt-2xl"
    >
      <div class="flex flex-1 items-center gap-lg">
        <p-dropdown
          v-if="systemStore.isCollapseSidebar"
          hoist
        >
          <span slot="trigger" class="cursor-pointer">
            <p-tooltip
              :content="authStore?.user?.name"
              hoist
            >
              <p-avatar
                label="User avatar"
                style="--size: 40px"
              ></p-avatar>
            </p-tooltip>
          </span>
          <p-menu>
            <p-menu-item @click="handleLogout">
              <span
                class="flex items-center gap-xs text-error-500"
              >
                Logout
                <p-icon-button
                  name="box-arrow-right"
                  label="Logout"
                ></p-icon-button>
              </span>
            </p-menu-item>
          </p-menu>
        </p-dropdown>
        <p-avatar
          v-else
          label="User avatar"
          style="--size: 40px"
        ></p-avatar>
        <div
          class="flex flex-col items-start"
          v-if="!systemStore.isCollapseSidebar"
        >
          <span class="text-sm font-semibold text-gray-700">
            {{ authStore?.user?.name }} </span
          ><span
            class="text-sm font-normal text-gray-600"
            v-if="authStore?.user?.email"
          >
            {{ authStore?.user?.email }}
          </span>
        </div>
      </div>
      <p-icon-button
        v-if="!systemStore.isCollapseSidebar"
        @click="handleLogout"
        name="box-arrow-right"
        label="Logout"
      ></p-icon-button>
    </div>
    <p-button
      circle
      class="absolute right-0 top-10 z-10 ml-auto translate-x-[50%]"
      @click="handleCollapseSidebar"
    >
      <p-icon
        name="chevron-left"
        label="Show"
        :class="{
          'rotate-180': systemStore.isCollapseSidebar,
          'rotate-0': !systemStore.isCollapseSidebar,
        }"
      ></p-icon>
    </p-button>
  </div>
</template>

<script setup lang="ts">
import { useAuthStore } from '@/modules/auth/store';
import sidebar, {
  SidebarRouter,
} from '@/components/sidebar/const';
import SidebarItem from '@/components/sidebar/SidebarItem.vue';
import { useRouter } from 'vue-router';
import { twMerge } from 'tailwind-merge';
import { useSystemStore } from '@/stores/system';

const systemStore = useSystemStore();
const router = useRouter();

const authStore = useAuthStore();

const handleLogout = () => {
  try {
    authStore.logout();
    router.push({ name: 'login' });
  } catch (error) {}
};

const handleCollapseSidebar = () => {
  systemStore.isCollapseSidebar =
    !systemStore.isCollapseSidebar;
  if (systemStore.isCollapseSidebar) {
    sidebar.forEach((i: SidebarRouter) => {
      i.isOpen = false;
    });
  }
};
</script>

<style scoped lang="scss">
#sidebar {
  @apply h-screen min-w-[60px] bg-white;
}

#footer {
  @apply relative w-full;
}
</style>

// src/components/common/Sidebar.tsx
import sidebar from '@/configs/sidebar';
import MenuItem from '@/components/common/MenuItem';
import { useNavigate } from 'react-router-dom';
import { SlIcon } from '@shoelace-style/shoelace/dist/react';
import { useTranslation } from 'react-i18next';
import { useAuthStore } from '@/features/auth/store';

interface ISidebarProps {
  onClose?: () => void;
}

export default function Sidebar(props: ISidebarProps) {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { logout } = useAuthStore();

  const handleLogout = async () => {
    await logout();
    navigate('/sign-in');
  }
  return (
    <div
      className="flex flex-col w-fit md:w-[264px] relative h-full overflow-hidden bg-[#1e1e2d] !text-[#494b74]"
      onClick={(e) => {
        e.stopPropagation();
      }}
    >
      <div
        className="w-full py-3 px-6 flex flex-row gap-3 bg-[#1A1A27] select-none cursor-pointer"
        onClick={() => navigate('/')}
      >
        <img
          src="/logo.png"
          alt="logo"
          className="h-12 shadow-md"
        />
        <div className="flex flex-col">
          <span className="font-medium text-xl text-white">
            LETGOAI
          </span>
          <span className="text-xs font-medium text-[var(--sl-color-primary-400)] tracking-wide uppercase">
            Affiliate center
          </span>
        </div>
      </div>
      <nav className="flex flex-1 flex-col w-full max-h-[calc(100vh-72px)] overflow-y-auto overflow-x-hidden pt-6">
        <ul role="list">
          {sidebar.map((i, index) => (
            <MenuItem key={index} data={i} 
              closeSidebar={props.onClose}
            />
          ))}
        </ul>
      </nav>
      <div className="w-full flex justify-center items-center p-4 gap-3 hover:opacity-80 active:opacity-80 active:bg-slate-50/20 border-t border-slate-50/20 cursor-pointer"
        onClick={() => {
          handleLogout();
        }}
      >
        <SlIcon
          name="box-arrow-right"
          className="text-red-500 w-5 h-5"
        ></SlIcon>
        <span className='text-white text-sm'>{t('system.sign-out')}</span>
      </div>
    </div>
  );
}
